version: '3'

services:
    httpd:
        image: httpd:latest
        restart: always
        ports:
            - 80:80
        volumes:
            - ./www:/usr/local/apache2/htdocs
    tomcat:
        image: tomcat
        restart: always
        ports:
            - 8088:8080
        volumes:
            - ./backend:/usr/local/tomcat/webapps
    jenkins:
        image: robsoncruz/jenkins-jv:latest
        ports:
            - '8080:8080'
            - '443:8443'
            - '50000:50000'
        environment:
            - JENKINS_PASSWORD=user
            - JENKINS_PASSWORD=aluno1234
        volumes:
            - 'jenkins_data:/bitnami/jenkins'
            - ./www:/app:rw
            - ./backend:/backend:rw
volumes:
  jenkins_data:
    driver: local